/* Core */
import { createSlice, type PayloadAction } from '@reduxjs/toolkit'

/* Instruments */
import { incrementAsync, signupAsync } from './thunks'
import { User } from '@/lib/type'

const initialState: UserSliceState = {
  user: {
    username: '',
    email_address: '',
    password: '',
  },
  status: 'idle',
}

export const userSlice = createSlice({
  name: 'user',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {

    // increment: (state) => {
    //   // Redux Toolkit allows us to write "mutating" logic in reducers. It
    //   // doesn't actually mutate the state because it uses the Immer library,
    //   // which detects changes to a "draft state" and produces a brand new
    //   // immutable state based off those changes
    //   state.value += 1
    // },
    // decrement: (state) => {
    //   state.value -= 1
    // },
    // // Use the PayloadAction type to declare the contents of `action.payload`
    // incrementByAmount: (state, action: PayloadAction<number>) => {
    //   state.value += action.payload
    // },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(signupAsync.pending, (state) => {
        state.status = 'loading'
      })
      .addCase(signupAsync.fulfilled, (state, action) => {
        state.status = 'idle'
        console.log(action)
        // state.user = action
      })
  },
})

/* Types */
export interface UserSliceState {
  user: User
  status: 'idle' | 'loading' | 'failed'
}
